### ISSUE TITLE
New gatt attributes

### ISSUE THREAD

**Issue by birdie1** [birdie1/victron#11]
The smartshunt sends out new data via gatt ble protocol. I already added remaining time and starter voltage.

I need some help to decode the other values. I found these values on my smartshunt:
victron_smartshunt_ble.py::91 Shunt1: Characteristic (65970383-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Rawvalue: b'\xff\x7f'
victron_smartshunt_ble.py::92 Shunt1: Characteristic (65970383-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Value signed: 32767.0 | Value unsigned: 32767.0
victron_smartshunt_ble.py::91 Shunt1: Characteristic (65970382-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Rawvalue: b'\xff\xff'
victron_smartshunt_ble.py::92 Shunt1: Characteristic (65970382-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Value signed: -1.0 | Value unsigned: 65535.0
victron_smartshunt_ble.py::91 Shunt1: Characteristic (6597edec-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Rawvalue: b'\xff\xff'
victron_smartshunt_ble.py::92 Shunt1: Characteristic (6597edec-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Value signed: -1.0 | Value unsigned: 65535.0
victron_smartshunt_ble.py::91 Shunt1: Characteristic (6597ffff-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Rawvalue: b''
victron_smartshunt_ble.py::92 Shunt1: Characteristic (6597ffff-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Value signed: 0.0 | Value unsigned: 0.0

Can somebody check, what values do you get? To get this output, just start a bluetooth-ble protocol smartshunt with debug option.
Thanks

**Comment by robwolff3** [comment]
Not sure if you see need output. Here is what I got
```
[INFO   ] (2023-03-14 16:05:32,337) victron_ble.py::45 HouseShunt: Connecting...
[INFO   ] (2023-03-14 16:05:35,865) victron_ble.py::45 HouseShunt: Connecting...
[DEBUG  ] (2023-03-14 16:05:35,915) victron_gatt_ble.py::71 HouseShunt: [E0:9E:8C:1D:D7:03] Resolved services
[DEBUG  ] (2023-03-14 16:05:35,915) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c940>
[DEBUG  ] (2023-03-14 16:05:35,927) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c820>
[DEBUG  ] (2023-03-14 16:05:35,949) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c790>
[DEBUG  ] (2023-03-14 16:05:35,964) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c8b0>
[DEBUG  ] (2023-03-14 16:05:35,987) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c460>
[DEBUG  ] (2023-03-14 16:05:36,009) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c4c0>
[DEBUG  ] (2023-03-14 16:05:36,039) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c310>
[DEBUG  ] (2023-03-14 16:05:36,062) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c190>
[DEBUG  ] (2023-03-14 16:05:36,077) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8c070>
[DEBUG  ] (2023-03-14 16:05:36,099) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8ee30>
[DEBUG  ] (2023-03-14 16:05:36,114) victron_gatt_ble.py::75 HouseShunt: Read value from characteristic <gatt.gatt_linux.Characteristic object at 0x7f6243c8f2b0>
[INFO   ] (2023-03-14 16:05:36,131) victron_gatt_ble.py::40 HouseShunt: Connect successful!
[WARNING] (2023-03-14 16:05:36,134) victron_smartshunt_ble.py::79 HouseShunt: Characteristic (65970383-4bda-4c1e-af4b-551c4cf74769) not found in known Table
[DEBUG  ] (2023-03-14 16:05:36,134) victron_smartshunt_ble.py::83 HouseShunt: Characteristic (65970383-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Rawvalue: b'\xff\x7f'
[DEBUG  ] (2023-03-14 16:05:36,134) victron_smartshunt_ble.py::84 HouseShunt: Characteristic (65970383-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Value signed: 32767.0 | Value unsigned: 32767.0
[WARNING] (2023-03-14 16:05:36,135) victron_smartshunt_ble.py::79 HouseShunt: Characteristic (65970382-4bda-4c1e-af4b-551c4cf74769) not found in known Table
[DEBUG  ] (2023-03-14 16:05:36,135) victron_smartshunt_ble.py::83 HouseShunt: Characteristic (65970382-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Rawvalue: b'\xff\xff'
[DEBUG  ] (2023-03-14 16:05:36,135) victron_smartshunt_ble.py::84 HouseShunt: Characteristic (65970382-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Value signed: -1.0 | Value unsigned: 65535.0
[WARNING] (2023-03-14 16:05:36,135) victron_smartshunt_ble.py::79 HouseShunt: Characteristic (6597edec-4bda-4c1e-af4b-551c4cf74769) not found in known Table
[DEBUG  ] (2023-03-14 16:05:36,135) victron_smartshunt_ble.py::83 HouseShunt: Characteristic (6597edec-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Rawvalue: b'\xff\xff'
[DEBUG  ] (2023-03-14 16:05:36,135) victron_smartshunt_ble.py::84 HouseShunt: Characteristic (6597edec-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Value signed: -1.0 | Value unsigned: 65535.0
[INFO   ] (2023-03-14 16:05:36,136) victron_smartshunt_ble.py::92 HouseShunt: Gathering data successful
[DEBUG  ] (2023-03-14 16:05:36,136) victron_ble.py::37 HouseShunt: Got last value, disconnecting...
[WARNING] (2023-03-14 16:05:38,819) victron_smartshunt_ble.py::79 HouseShunt: Characteristic (6597ffff-4bda-4c1e-af4b-551c4cf74769) not found in known Table
[DEBUG  ] (2023-03-14 16:05:38,819) victron_smartshunt_ble.py::83 HouseShunt: Characteristic (6597ffff-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Rawvalue: b''
[DEBUG  ] (2023-03-14 16:05:38,819) victron_smartshunt_ble.py::84 HouseShunt: Characteristic (6597ffff-4bda-4c1e-af4b-551c4cf74769) not found in known Table | Value signed: 0.0 | Value unsigned: 0.0
[INFO   ] (2023-03-14 16:05:38,819) victron_smartshunt_ble.py::92 HouseShunt: Gathering data successful
[DEBUG  ] (2023-03-14 16:05:38,819) victron_ble.py::37 HouseShunt: Got last value, disconnecting...
[INFO   ] (2023-03-14 16:05:38,823) victron_gatt_ble.py::52 HouseShunt: Disconnect successful!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 1371, in run
    self.function(*self.args, **self.kwargs)
  File "/victron/victron.py", line 25, in victron_thread
    v.connect_disconnect_loop()
  File "/victron/lib/victron.py", line 52, in connect_disconnect_loop
    self.victron_type.connect_disconnect_loop(self.cmd, self.config['timer'])
  File "/victron/lib/victron_ble/victron_ble.py", line 75, in connect_disconnect_loop
    next_time = datetime.now() + timedelta(seconds=timer['bluetooth-ble']['repeat'])
KeyError: 'bluetooth-ble'
```
